[package]
name = "os"
version = "0.1.0"
authors = ["hdg"]
edition = "2018"

[dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }